### ISSUE TITLE
Suggestion for the README.md file to include

### ISSUE THREAD

**Issue by IT-Tool** [vinser/pixyne#21]
I have tested the program on Linux x86_64 and it works (you can add it to the table).

And if I might make a suggestion, for a successful build on Linux, you might consider adding the following items to the https://github.com/vinser/pixyne#building section.

1. git clone https://github.com/vinser/pixyne.git
2. cd ./pixyne/
3. go build (if the build fails, you need to run the command: "**go get**". And try again: "**go build**")
4. ./pixyne

**Comment by vinser** [comment]
Thanks for testing the app. 
The table contains info about most common used pre-build binaries that resides in release. They can build rarely used OS/platform binaries if needed.
While being read your suggestion I've got that I missed dot in the build command. It should be `go build .`
